### ISSUE TITLE
Confused Question

### ISSUE THREAD

**Issue by StartMvoe** [pongthang/generative-AI-anomaly-detection#2]
Well, I find that the work of this project is relatedto the paper “Fast Unsupervised Brain Anomaly Detection and Segmentation with Diffusion Models” ( https://arxiv.org/pdf/2206.03461) with different datasets. But there is a difference that confused me. The paper states that “After training the VQ-VAE and DDPM on normal data, we use VQ-VAE to obtain the latent representation z of the test images. After that, we use the DDPM’s forward process to obtain the noisy representations zt across the Markov chain.” Yes, the “z” obtained from “z = autoencoderkl.sampling(z_mu, z_sigma)” adds noise through the forward process, while the “z” denoises through the reverse process in the project (In the anomaly_detection_knee.ipynb, scheduler.reversed_step(model_output, t, current_img), where the current_img is z). The “z” can be seen as z_0 in the whole diffusion process, we can get each z_t through the forward process, but how can it still do the reverse process? Could you please explain the logic of this code? Sincerely!

**Comment by pongthang** [comment]
Hello, this project is based on this https://arxiv.org/pdf/2207.12268 paper. I don't read the paper you have provided but I will provide the overview of the implementation which is similar to the paper that I mentioned above. In this project first the input image is converted into latent space 'z' use VAE. From this some noise is added through forward diffusion. From this somewhat noisy latent space the backward diffusion process is performed toward the healthy image latent space. After completing the steps, the new latent space z` is again converted back to image using VAE.

**Comment by pongthang** [comment]
Reason why we need to put noise is that we need to remove some features of the input image (unhealthy image )  so that we can generate the healthy image from this .But ,  still we need to keep some important features like shape , size of the image.
BTW , implementation of the paper can be found here. https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/anomaly_detection/2d_classifierfree_guidance_anomalydetection_tutorial.ipynb . Here they do not use VAE or latent space. I add the VAE part.

**Comment by StartMvoe** [comment]
Great! The paper you provided answered all my questions. Thank you for patient and detailed comments. Best wishes!

**Comment by pongthang** [comment]
Welcome...
